version: '3.8'

services:

  jupyterlab:

    image: dddlab/base-python:latest

    build:
      context: ./
      dockerfile: Dockerfile

    ports:
      - 443:8888

    user: root

    environment:
      - RESTARTABLE=yes
      - GEN_CERT=yes
      - GRANT_SUDO=yes
      - JUPYTER_TOKEN=asdf
      - SHELL=/bin/zsh
      # - DOCKER_STACKS_JUPYTER_CMD=lab

    volumes:
      - ${PWD}:/home/jovyan/work

    command:
      - start-notebook.sh
      - --ServerApp.password=sha1:3c5a4b522718:bf63e22afd2f2d08d9ef0262f69697c9fa4baa2c