apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "diy.fullname" . }}-notebook
  labels:
    app: {{ template "diy.name" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "diy.chart" . }}
    component: notebook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "diy.name" . }}
      release: {{ .Release.Name | quote }}
      component: notebook
  template:
    metadata:
      labels:
        app: {{ template "diy.name" . }}
        release: {{ .Release.Name | quote }}
        component: notebook
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.notebook.image.repository }}:{{ .Values.notebook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.notebook.image.pullPolicy }}
          {{- if eq .Values.language "python" }}
          command: ["/bin/sh", "-c"]
          args: # default password is "diy-cloud"
            - > 
              /usr/local/bin/start-notebook.sh
              --ServerApp.password="{{ .Values.notebook.ui.hashedPassword }}"
              --LabApp.default_url=/lab/workspaces/lab
          env:
            - name: "DASK_SCHEDULER_ADDRESS"
              value: "{{ include "diy.fullname" . }}-scheduler:{{ .Values.scheduler.controller.targetPort }}"
            - name: "DASK_DASHBOARD_ADDRESS"
              value: "{{ include "diy.fullname" . }}-scheduler:{{ .Values.scheduler.ui.targetPort }}"
          {{ else if eq .Values.language "R" }}
          command: ["/bin/sh", "-c"]
          args: # default password is "diy-cloud"
            - > 
              /opt/conda/bin/future-vars.sh 
              --run-mode scheduler 
              --port {{ .Values.notebook.controller.targetPort }}
              --n-workers {{ .Values.worker.replicaCount }};
              /usr/local/bin/start-notebook.sh
              --ServerApp.password="{{ .Values.notebook.ui.hashedPassword }}"
              --LabApp.default_url="/rstudio"
          {{ end }}
          resources:
            {{- toYaml .Values.notebook.resources | nindent 12 }}